### PR TITLE
replaced dxDao with welcome, added dxDao group that above everything …

### LINKED ISSUE #5: Introduce spacing to Categories
Hopefully this makes sense as a separate issue, since the first was primarily content focused.

Replace the "DXdao" category with "Welcome". 

Add a unclickable group labelled "DXdao". Include everything below this except "Get connected".

Remove "Get Connected", and create a group with the same name.

Include all links at this higher level, making them visible without expanding a "Get connected" category.

.

Below I have included an example of Gitbook, where "Welcome" is ungrouped and above all others. "Primedao" is unclickable and is used to group together the relevant categories. "Links" is unclickable and is used to include those links at all times. 

[Here the site if that is easier.](https://docs.primedao.io/)

image

If formatting in such a way is not possible with Just the docs, ping me and I will work on a solution.

### PR DESCRIPTION
**Pull request by Mi-Lan**
closes #5 
- I also removed the the little arrow down that you see with rest of categories
- The dxDao text can be changed and formatted in whatever way this is just some mock version..

### CODE REVIEW

**Comment by KeenanLukeOM** [comment]
This looks great, I love that the DXdao text is bigger and centered when compared to the categories.

The only thing, would it be possible to do this for "Get Connected" as well?

**Comment by Mi-Lan** [comment]
> This looks great, I love that the DXdao text is bigger and centered when compared to the categories.
> 
> The only thing, would it be possible to do this for "Get Connected" as well?

@KeenanLukeOM I added text styling like for dxDao also my suggestion is to add icons for every getConnected link next to it ...

**Comment by KeenanLukeOM** [comment]
This looks awesome! One quick fix, it looks like "Get connected" still gets highlighted on hover despite not being clickable. Heres a photo.

image

Regarding adding icons, I agree fully. We should add favicons to the left of each entry. If you have a better resource, feel free to use it. I couldn't find appropriately sized favicons in Omen, Swapr, or Rails' source code.

[Favicons.zip](https://github.com/Mi-Lan/dxDaoBlog/files/6110942/Favicons.zip)

**Comment by KeenanLukeOM** [comment]
One thing I noticed, highlighting a social scales with the text rather than highlighting the whole box. Let me picture it.

image

Here is a fully highlighted category. ^

image

Here is a highlighted social, notice how it doesn't reach the right of the box. ^

image

Another highlighted social, notice how it is a different length than the previous social. ^

**Pull request merged**
